name: Tox

on: [push, pull_request]

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Run pylinter
        run: docker run --rm -v $PWD/tests/:/opt/app-root/src/tests/ quay.io/resource-hub-dev/rhub-api:test
      #- name: Install Tox
      #  run: pip install tox
      #- name: Run Tox
      #  run: tox
